JMC-5967: Generated code should optionally capture any thrown exceptions and rethrow
thegreystone/jmc-old pull request #3
Opened 2019-07-24 13:56 UTC by tabjy

Hello Marcus,

This patch implements [JMC-5967](https://bugs.openjdk.java.net/browse/JMC-5967). An optional configuration, `rethrow`, is enables the generated code to capture any thrown exceptions, emit the event, and then re-throw. Test cases are included.

Please let me know what you think.

Regards,
(Arvin) Kangcheng Xu

2019-07-24 16:40 UTC, thegreystone requested changes

2019-07-24 16:40 UTC, thegreystone commented on core/org.openjdk.jmc.agent/src/main/java/org/openjdk/jmc/agent/jfr/impl/JFRMethodAdvisor.java
> +		this.shouldInstrumentThrow = !transformDescriptor.isUseRethrow(); // don't instrument inner throws is rethrow is enabled
s/is/if

2019-07-24 16:40 UTC, thegreystone commented on core/org.openjdk.jmc.agent/src/main/java/org/openjdk/jmc/agent/jfr/impl/JFRMethodAdvisor.java
> +			visitTryCatchBlock(tryBegin, tryEnd, tryEnd, "java/lang/Exception");
Define java/lang/Exception constant.

2019-07-24 16:40 UTC, thegreystone commented on core/org.openjdk.jmc.agent/src/main/java/org/openjdk/jmc/agent/jfr/impl/JFRMethodAdvisor.java
> +			visitTryCatchBlock(tryBegin, tryEnd, tryEnd, "java/lang/Exception");
Come to think of it, we probably also want to emit the event in case of errors - this should probably be Throwable.

2019-07-24 16:40 UTC, thegreystone commented on core/org.openjdk.jmc.agent/src/main/java/org/openjdk/jmc/agent/jfrnext/impl/JFRNextMethodAdvisor.java
> +		this.shouldInstrumentThrow = !transformDescriptor.isUseRethrow(); // don't instrument inner throws is rethrow is enabled
Same here - comment fix

2019-07-24 16:40 UTC, thegreystone commented on core/org.openjdk.jmc.agent/src/main/java/org/openjdk/jmc/agent/jfrnext/impl/JFRNextMethodAdvisor.java
> +			visitTryCatchBlock(tryBegin, tryEnd, tryEnd, "java/lang/Exception");
Same constant. Should probably be Throwable.

2019-07-24 16:40 UTC, thegreystone commented on core/org.openjdk.jmc.agent/src/test/java/org/openjdk/jmc/agent/test/InstrumentMe.java
> +	public static void printHelloWorldJFR8() throws InterruptedException {
Commendable to add tests! Good job! :)

2019-07-24 19:09 UTC, tabjy commented on core/org.openjdk.jmc.agent/src/main/java/org/openjdk/jmc/agent/jfr/impl/JFRMethodAdvisor.java
> +		this.shouldInstrumentThrow = !transformDescriptor.isUseRethrow(); // don't instrument inner throws is rethrow is enabled
updated in 006487a7e520c63600e271ba82b5d0ffd21d2bb9

2019-07-24 19:09 UTC, tabjy commented on core/org.openjdk.jmc.agent/src/main/java/org/openjdk/jmc/agent/jfr/impl/JFRMethodAdvisor.java
> +			visitTryCatchBlock(tryBegin, tryEnd, tryEnd, "java/lang/Exception");
updated in 006487a7e520c63600e271ba82b5d0ffd21d2bb9

2019-07-24 19:09 UTC, tabjy commented on core/org.openjdk.jmc.agent/src/main/java/org/openjdk/jmc/agent/jfrnext/impl/JFRNextMethodAdvisor.java
> +		this.shouldInstrumentThrow = !transformDescriptor.isUseRethrow(); // don't instrument inner throws is rethrow is enabled
updated in 006487a7e520c63600e271ba82b5d0ffd21d2bb9

2019-07-24 19:09 UTC, tabjy commented on core/org.openjdk.jmc.agent/src/test/java/org/openjdk/jmc/agent/test/InstrumentMe.java
> +	public static void printHelloWorldJFR8() throws InterruptedException {
Thank you!

2019-07-24 19:09 UTC, tabjy commented on core/org.openjdk.jmc.agent/src/main/java/org/openjdk/jmc/agent/jfrnext/impl/JFRNextMethodAdvisor.java
> +			visitTryCatchBlock(tryBegin, tryEnd, tryEnd, "java/lang/Exception");
updated in 006487a7e520c63600e271ba82b5d0ffd21d2bb9

2019-07-24 19:11 UTC, tabjy commented
Requested changes have been applied with commit 006487a7e520c63600e271ba82b5d0ffd21d2bb9. Thank you!

2019-10-19 14:00 UTC, thegreystone reviewed
Note that the point of JMC-5967 is to defensively capture any runtime exceptions thrown in code called within the method, so that events are properly committed.

A good test for this would be to let a one of the test methods to be instrumented call another method which throws a runtime exceptions, and see if events are properly emitted

2019-10-22 09:57 UTC, thegreystone commented
Excellent work! Looks good. Merging this. We may want to rethink the naming of rethrow, but that can be done in a separate PR.

2019-10-22 09:57 UTC, thegreystone approved these changes

2019-10-22 09:58 UTC, merged