JMC-5458: Support Class-Redefinitions
thegreystone/jmc-old pull request #4
Opened 2019-08-01 18:58 UTC by jessyec-s

Hi Marcus, 

This patch addresses [JMC-5458](https://bugs.openjdk.java.net/projects/JMC/issues/JMC-5458?filter=allopenissues)  : 
1. Handle name collisions with existing classes
2. Cleanly revert the instrumentation of a method to a version prior to instrumenting

Please let me know what you think,

Jessye Coleman-Shapiro

2019-08-09 15:37 UTC, thegreystone requested changes

2019-08-09 15:37 UTC, thegreystone commented on core/org.openjdk.jmc.agent/src/main/java/org/openjdk/jmc/agent/jmx/AgentController.java
> +		boolean revertAll = xmlDescription == null ? true : (xmlDescription.isBlank() ? true : false);
isBlank is JDK 11+ - note that this agent can be used with pre-JDK 11 JVMs, even JDK 7 Oracle JVMs.

2019-08-09 15:37 UTC, thegreystone commented on core/org.openjdk.jmc.agent/README.md
> +At runtime the agent can be used to revert the instrumentation of a method to a version prior to instrumenting.  By supplying the revertToPreInstrumentation function with a XML description of transfo
I think a better solution to this may be to not have a specific revert method, but rather just have one method to setTransforms(String xmlDescription), it takes the state we want to achieve - then get rid of update, transform etc. Yes, this requires that the client keep track of the wanted state and changes to it, and it if multiple clients are involved, this may complicate matters, but it also reduces complexity. What do you think?

2019-08-09 16:13 UTC, jessyec-s commented on core/org.openjdk.jmc.agent/README.md
> +At runtime the agent can be used to revert the instrumentation of a method to a version prior to instrumenting.  By supplying the revertToPreInstrumentation function with a XML description of transfo
Right now the revertToPreInstrumentation method replaces the instrumentation in the registry with that described in the passed in xml description and then retransforms the related classes based on their _original_ byte code. Is this what you mean by "taking the state you want to achieve"? Also what _update_ and _transform_ functionality are you referring to? Do you mean the update function that is called by retransformClasses?

2019-08-14 14:29 UTC, jessyec-s commented on core/org.openjdk.jmc.agent/src/main/java/org/openjdk/jmc/agent/jmx/AgentController.java
> +		boolean revertAll = xmlDescription == null ? true : (xmlDescription.isBlank() ? true : false);
fixed 19d7d8b

2019-10-19 14:30 UTC, thegreystone commented on core/org.openjdk.jmc.agent/README.md
> +At runtime the agent can be used to revert the instrumentation of a method to a version prior to instrumenting.  By supplying the revertToPreInstrumentation function with a XML description of transfo
Hi Jessye!

What I meant was that an easier API might be to just have one method to specify what you would want the transformed state to be, taking classes no longer mentioned in the xml description (but noted in the registry as transformed) back to their original byte code, and retransforming classes when the description differ for already transformed classes (or classes previously not transformed), and leaving classes where the transform description does not differ be.

2019-10-22 14:34 UTC, jessyec-s commented on core/org.openjdk.jmc.agent/README.md
> +At runtime the agent can be used to revert the instrumentation of a method to a version prior to instrumenting.  By supplying the revertToPreInstrumentation function with a XML description of transfo
This makes sense to me! I have made a general function, setTransforms(xmlDescription), in https://github.com/thegreystone/jmc/pull/4/commits/9c8a1d69bf0488c64f56c18ce8adecc7ba8a6549. I have removed the update and retransformClasses functions.  Let me know what you think.

2019-10-23 14:25 UTC, thegreystone commented on core/org.openjdk.jmc.agent/README.md
> +At runtime the agent can be used to revert the instrumentation of a method to a version prior to instrumenting.  By supplying the revertToPreInstrumentation function with a XML description of transfo
Hi Jessye!

Good job - looks great!

2019-10-23 14:26 UTC, thegreystone approved these changes

2019-10-23 14:26 UTC, merged

2019-10-23 14:50 UTC, jessyec-s commented on core/org.openjdk.jmc.agent/README.md
> +At runtime the agent can be used to revert the instrumentation of a method to a version prior to instrumenting.  By supplying the revertToPreInstrumentation function with a XML description of transfo
Thanks Marcus! I just realised that I forgot to update this readme description to reflect the changes regarding the setTransforms function.  Should I make another pr with an updated description?

2019-10-24 06:09 UTC, thegreystone commented on core/org.openjdk.jmc.agent/README.md
> +At runtime the agent can be used to revert the instrumentation of a method to a version prior to instrumenting.  By supplying the revertToPreInstrumentation function with a XML description of transfo
Please do!